title: Matt Konda
description: |
  Entrepreneur | 
  Security Leader | 
  Developer
owner: Matt Konda
first_published: 2012
email: matt@mattkonda.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mattkonda.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/mkonda
  github: https://github.com/mkonda
  linkedin-square: https://linkedin.com/in/matthewkonda
  google-plus-square: https://plus.google.com/+MattKonda
  email: mailto:mattkonda@gmail.com
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown

future: true

#sass:
#  style: compressed
