title: Matt Konda
description: |
  Entrepreneur | 
  Security Leader | 
  Developer
owner: Matt Konda
first_published: 2012
email: matt@mattkonda.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mattkonda.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/mkonda
  github: https://github.com/mkonda
  linkedin-square: https://linkedin.com/in/matthewkonda
  email: mailto:matt.konda@hey.com
  youtube-square:
  leanpub: https://leanpub.com/u/mkonda

# Build settings
markdown: kramdown

future: true

#sass:
#  style: compressed


# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /assets/images/mk.png
description: Matt Konda
author:
  name: Matt Konda
  email: matt.konda@hey.com
  twitter: https://twitter.com/mkonda
social:
  name: 
  links:
    - https://github.com/mkonda/
    - https://mattkonda.com/

# -----
# Build

timezone: Etc/UTC
paginate: 10
paginate_path: "/blog/:num/"
permalink: /:year/:month/:day/:slug/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 1500
          height: 2500
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
